/* soapStub.h
   Generated by gSOAP 2.8.135 for webservice/ws-cups-fax.h

gSOAP XML Web services tools
Copyright (C) 2000,2024, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#define SOAP_NAMESPACE_OF_ns1	"http://ws.gtc.net/"

#ifndef soapStub_H
#define soapStub_H
#include "stdsoap2.h"
#if GSOAP_VERSION != 208135
# error "GSOAP VERSION 208135 MISMATCH IN GENERATED CODE VERSUS LIBRARY CODE: PLEASE REINSTALL PACKAGE"
#endif


/******************************************************************************\
 *                                                                            *
 * Types with Custom Serializers                                              *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Structs and Unions                                                         *
 *                                                                            *
\******************************************************************************/

struct xsd__base64Binary;	/* webservice/ws-cups-fax.h:144 */
struct ns1__Entries;	/* webservice/ws-cups-fax.h:187 */
struct ns1__Entry;	/* webservice/ws-cups-fax.h:191 */
struct ns1__ArrayOfString;	/* webservice/ws-cups-fax.h:212 */
struct ns1__ArrayOfStrings;	/* webservice/ws-cups-fax.h:248 */
struct ns1__File;	/* webservice/ws-cups-fax.h:216 */
struct ns1__Table;	/* webservice/ws-cups-fax.h:218 */
struct ns1__version;	/* webservice/ws-cups-fax.h:299 */
struct ns1__versionResponse;	/* webservice/ws-cups-fax.h:312 */
struct ns1__test;	/* webservice/ws-cups-fax.h:327 */
struct ns1__testResponse;	/* webservice/ws-cups-fax.h:340 */
struct ns1__reload;	/* webservice/ws-cups-fax.h:355 */
struct ns1__reloadResponse;	/* webservice/ws-cups-fax.h:368 */
struct __ns1__execResponse;	/* webservice/ws-cups-fax.h:481 */
struct __ns1__exec;	/* webservice/ws-cups-fax.h:530 */
struct __ns1__version;	/* webservice/ws-cups-fax.h:585 */
struct __ns1__test;	/* webservice/ws-cups-fax.h:640 */
struct __ns1__reload;	/* webservice/ws-cups-fax.h:695 */

/* webservice/ws-cups-fax.h:144 */
#ifndef SOAP_TYPE_xsd__base64Binary
#define SOAP_TYPE_xsd__base64Binary (7)
/* binary data attached as MTOM/MIME/DIME attachment or included as *`xsd:base64Binary`* base64: */
struct xsd__base64Binary {
        unsigned char *__ptr;
        int __size;
        /** Optional element 'id' of XML schema type 'xsd:string' */
        char *id;
        /** Optional element 'type' of XML schema type 'xsd:string' */
        char *type;
        /** Optional element 'options' of XML schema type 'xsd:string' */
        char *options;
};
#endif

/* webservice/ws-cups-fax.h:187 */
#ifndef SOAP_TYPE_ns1__Entries
#define SOAP_TYPE_ns1__Entries (13)
/* complex XML schema type 'ns1:Entries': */
struct ns1__Entries {
        /** Sequence of 0 to 1024 elements 'ns1:item' of XML schema type 'ns1:Entry' stored in dynamic array item of length __sizeitem */
        int __sizeitem;
        struct ns1__Entry *item;
};
#endif

/* webservice/ws-cups-fax.h:191 */
#ifndef SOAP_TYPE_ns1__Entry
#define SOAP_TYPE_ns1__Entry (14)
/* complex XML schema type 'ns1:Entry': */
struct ns1__Entry {
        /** Required element 'ns1:key' of XML schema type 'ns1:string' */
        char *key;
        /** Optional element 'ns1:value' of XML schema type 'ns1:string' */
        char *value;
        /** Optional element 'ns1:intValue' of XML schema type 'xsd:int' */
        int *intValue;
        /** Optional element 'ns1:values' of XML schema type 'ns1:ArrayOfString' */
        struct ns1__ArrayOfString *values;
        /** Sequence of 0 to 10 elements 'ns1:files' of XML schema type 'ns1:File' stored in dynamic array files of length __sizefiles */
        int __sizefiles;
        struct ns1__File *files;
        /** Optional element 'ns1:table' of XML schema type 'ns1:Table' */
        struct ns1__Table *table;
};
#endif

/* webservice/ws-cups-fax.h:212 */
#ifndef SOAP_TYPE_ns1__ArrayOfString
#define SOAP_TYPE_ns1__ArrayOfString (17)
/* complex XML schema type 'ns1:ArrayOfString': */
struct ns1__ArrayOfString {
        /** Sequence of 0 to 1024 elements 'ns1:item' of XML schema type 'ns1:string' stored in dynamic array item of length __sizeitem */
        int __sizeitem;
        char **item;
};
#endif

/* webservice/ws-cups-fax.h:248 */
#ifndef SOAP_TYPE_ns1__ArrayOfStrings
#define SOAP_TYPE_ns1__ArrayOfStrings (24)
/* complex XML schema type 'ns1:ArrayOfStrings': */
struct ns1__ArrayOfStrings {
        /** Sequence of 0 to 1024 elements 'ns1:item' of XML schema type 'ns1:ArrayOfString' stored in dynamic array item of length __sizeitem */
        int __sizeitem;
        struct ns1__ArrayOfString *item;
};
#endif

/* webservice/ws-cups-fax.h:216 */
#ifndef SOAP_TYPE_ns1__File
#define SOAP_TYPE_ns1__File (19)
/* complex XML schema type 'ns1:File': */
struct ns1__File {
        /** Required element 'ns1:name' of XML schema type 'ns1:string' */
        char *name;
        /** Required element 'ns1:data' of XML schema type 'ns1:base64Binary' */
        struct xsd__base64Binary data;
};
#endif

/* webservice/ws-cups-fax.h:218 */
#ifndef SOAP_TYPE_ns1__Table
#define SOAP_TYPE_ns1__Table (21)
/* complex XML schema type 'ns1:Table': */
struct ns1__Table {
        /** Required element 'ns1:head' of XML schema type 'ns1:ArrayOfString' */
        struct ns1__ArrayOfString *head;
        /** Required element 'ns1:fields' of XML schema type 'ns1:ArrayOfStrings' */
        struct ns1__ArrayOfStrings *fields;
};
#endif

/* webservice/ws-cups-fax.h:299 */
#ifndef SOAP_TYPE_ns1__version
#define SOAP_TYPE_ns1__version (26)
/* complex XML schema type 'ns1:version': */
struct ns1__version {
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* empty struct is a GNU extension */
#endif
};
#endif

/* webservice/ws-cups-fax.h:312 */
#ifndef SOAP_TYPE_ns1__versionResponse
#define SOAP_TYPE_ns1__versionResponse (27)
/* complex XML schema type 'ns1:versionResponse': */
struct ns1__versionResponse {
        /** Required element 'ns1:versionResponse' of XML schema type 'ns1:string' */
        char *versionResponse;
};
#endif

/* webservice/ws-cups-fax.h:327 */
#ifndef SOAP_TYPE_ns1__test
#define SOAP_TYPE_ns1__test (28)
/* complex XML schema type 'ns1:test': */
struct ns1__test {
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* empty struct is a GNU extension */
#endif
};
#endif

/* webservice/ws-cups-fax.h:340 */
#ifndef SOAP_TYPE_ns1__testResponse
#define SOAP_TYPE_ns1__testResponse (29)
/* complex XML schema type 'ns1:testResponse': */
struct ns1__testResponse {
        /** Required element 'ns1:testResponse' of XML schema type 'xsd:int' */
        int testResponse;
};
#endif

/* webservice/ws-cups-fax.h:355 */
#ifndef SOAP_TYPE_ns1__reload
#define SOAP_TYPE_ns1__reload (30)
/* complex XML schema type 'ns1:reload': */
struct ns1__reload {
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* empty struct is a GNU extension */
#endif
};
#endif

/* webservice/ws-cups-fax.h:368 */
#ifndef SOAP_TYPE_ns1__reloadResponse
#define SOAP_TYPE_ns1__reloadResponse (31)
/* complex XML schema type 'ns1:reloadResponse': */
struct ns1__reloadResponse {
        /** Required element 'ns1:reloadResponse' of XML schema type 'xsd:int' */
        int reloadResponse;
};
#endif

/* webservice/ws-cups-fax.h:481 */
#ifndef SOAP_TYPE___ns1__execResponse
#define SOAP_TYPE___ns1__execResponse (32)
/* Wrapper: */
struct __ns1__execResponse {
        /** Optional element 'ns1:entries' of XML schema type 'ns1:Entries' */
        struct ns1__Entries *ns1__entries;
};
#endif

/* webservice/ws-cups-fax.h:530 */
#ifndef SOAP_TYPE___ns1__exec
#define SOAP_TYPE___ns1__exec (36)
/* Wrapper: */
struct __ns1__exec {
        /** Optional element 'ns1:entries' of XML schema type 'ns1:Entries' */
        struct ns1__Entries *ns1__entries;
};
#endif

/* webservice/ws-cups-fax.h:585 */
#ifndef SOAP_TYPE___ns1__version
#define SOAP_TYPE___ns1__version (40)
/* Wrapper: */
struct __ns1__version {
        /** Optional element 'ns1:version' of XML schema type 'ns1:version' */
        struct ns1__version *ns1__version;
};
#endif

/* webservice/ws-cups-fax.h:640 */
#ifndef SOAP_TYPE___ns1__test
#define SOAP_TYPE___ns1__test (44)
/* Wrapper: */
struct __ns1__test {
        /** Optional element 'ns1:test' of XML schema type 'ns1:test' */
        struct ns1__test *ns1__test;
};
#endif

/* webservice/ws-cups-fax.h:695 */
#ifndef SOAP_TYPE___ns1__reload
#define SOAP_TYPE___ns1__reload (48)
/* Wrapper: */
struct __ns1__reload {
        /** Optional element 'ns1:reload' of XML schema type 'ns1:reload' */
        struct ns1__reload *ns1__reload;
};
#endif

/* webservice/ws-cups-fax.h:770 */
#ifndef WITH_NOGLOBAL
#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (49)
/* SOAP_ENV__Header: */
struct SOAP_ENV__Header {
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* empty struct is a GNU extension */
#endif
};
#endif
#endif

/* webservice/ws-cups-fax.h:770 */
#ifndef WITH_NOGLOBAL
#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (50)
/* Type SOAP_ENV__Code is a recursive data type, (in)directly referencing itself through its (base or derived class) members */
/* SOAP_ENV__Code: */
struct SOAP_ENV__Code {
        /** Optional element 'SOAP-ENV:Value' of XML schema type 'xsd:QName' */
        char *SOAP_ENV__Value;
        /** Optional element 'SOAP-ENV:Subcode' of XML schema type 'SOAP-ENV:Code' */
        struct SOAP_ENV__Code *SOAP_ENV__Subcode;
};
#endif
#endif

/* webservice/ws-cups-fax.h:770 */
#ifndef WITH_NOGLOBAL
#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (52)
/* SOAP_ENV__Detail: */
struct SOAP_ENV__Detail {
        char *__any;
        /** Any type of element 'fault' assigned to fault with its SOAP_TYPE_<typename> assigned to __type */
        /** Do not create a cyclic data structure through this member unless SOAP encoding or SOAP_XML_GRAPH are used for id-ref serialization */
        int __type;
        void *fault;
};
#endif
#endif

/* webservice/ws-cups-fax.h:770 */
#ifndef WITH_NOGLOBAL
#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (55)
/* SOAP_ENV__Reason: */
struct SOAP_ENV__Reason {
        /** Optional element 'SOAP-ENV:Text' of XML schema type 'xsd:string' */
        char *SOAP_ENV__Text;
};
#endif
#endif

/* webservice/ws-cups-fax.h:770 */
#ifndef WITH_NOGLOBAL
#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (56)
/* SOAP_ENV__Fault: */
struct SOAP_ENV__Fault {
        /** Optional element 'faultcode' of XML schema type 'xsd:QName' */
        char *faultcode;
        /** Optional element 'faultstring' of XML schema type 'xsd:string' */
        char *faultstring;
        /** Optional element 'faultactor' of XML schema type 'xsd:string' */
        char *faultactor;
        /** Optional element 'detail' of XML schema type 'SOAP-ENV:Detail' */
        struct SOAP_ENV__Detail *detail;
        /** Optional element 'SOAP-ENV:Code' of XML schema type 'SOAP-ENV:Code' */
        struct SOAP_ENV__Code *SOAP_ENV__Code;
        /** Optional element 'SOAP-ENV:Reason' of XML schema type 'SOAP-ENV:Reason' */
        struct SOAP_ENV__Reason *SOAP_ENV__Reason;
        /** Optional element 'SOAP-ENV:Node' of XML schema type 'xsd:string' */
        char *SOAP_ENV__Node;
        /** Optional element 'SOAP-ENV:Role' of XML schema type 'xsd:string' */
        char *SOAP_ENV__Role;
        /** Optional element 'SOAP-ENV:Detail' of XML schema type 'SOAP-ENV:Detail' */
        struct SOAP_ENV__Detail *SOAP_ENV__Detail;
};
#endif
#endif

/******************************************************************************\
 *                                                                            *
 * Typedefs                                                                   *
 *                                                                            *
\******************************************************************************/


/* (built-in):0 */
#ifndef SOAP_TYPE__XML
#define SOAP_TYPE__XML (5)
typedef char *_XML;
#endif

/* (built-in):0 */
#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (6)
typedef char *_QName;
#endif

/* webservice/ws-cups-fax.h:162 */
#ifndef SOAP_TYPE_ns1__string
#define SOAP_TYPE_ns1__string (11)
typedef char *ns1__string;
#endif

/* webservice/ws-cups-fax.h:167 */
#ifndef SOAP_TYPE_ns1__base64Binary
#define SOAP_TYPE_ns1__base64Binary (12)
typedef struct xsd__base64Binary ns1__base64Binary;
#endif

/******************************************************************************\
 *                                                                            *
 * Serializable Types                                                         *
 *                                                                            *
\******************************************************************************/


/* char has binding name 'byte' for type 'xsd:byte' */
#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (3)
#endif

/* int has binding name 'int' for type 'xsd:int' */
#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (1)
#endif

/* unsigned char has binding name 'unsignedByte' for type 'xsd:unsignedByte' */
#ifndef SOAP_TYPE_unsignedByte
#define SOAP_TYPE_unsignedByte (9)
#endif

/* unsigned int has binding name 'unsignedInt' for type 'xsd:unsignedInt' */
#ifndef SOAP_TYPE_unsignedInt
#define SOAP_TYPE_unsignedInt (8)
#endif

/* struct SOAP_ENV__Fault has binding name 'SOAP_ENV__Fault' for type '' */
#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (56)
#endif

/* struct SOAP_ENV__Reason has binding name 'SOAP_ENV__Reason' for type '' */
#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (55)
#endif

/* struct SOAP_ENV__Detail has binding name 'SOAP_ENV__Detail' for type '' */
#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (52)
#endif

/* struct SOAP_ENV__Code has binding name 'SOAP_ENV__Code' for type '' */
#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (50)
#endif

/* struct SOAP_ENV__Header has binding name 'SOAP_ENV__Header' for type '' */
#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (49)
#endif

/* struct ns1__reloadResponse has binding name 'ns1__reloadResponse' for type 'ns1:reloadResponse' */
#ifndef SOAP_TYPE_ns1__reloadResponse
#define SOAP_TYPE_ns1__reloadResponse (31)
#endif

/* struct ns1__reload has binding name 'ns1__reload' for type 'ns1:reload' */
#ifndef SOAP_TYPE_ns1__reload
#define SOAP_TYPE_ns1__reload (30)
#endif

/* struct ns1__testResponse has binding name 'ns1__testResponse' for type 'ns1:testResponse' */
#ifndef SOAP_TYPE_ns1__testResponse
#define SOAP_TYPE_ns1__testResponse (29)
#endif

/* struct ns1__test has binding name 'ns1__test' for type 'ns1:test' */
#ifndef SOAP_TYPE_ns1__test
#define SOAP_TYPE_ns1__test (28)
#endif

/* struct ns1__versionResponse has binding name 'ns1__versionResponse' for type 'ns1:versionResponse' */
#ifndef SOAP_TYPE_ns1__versionResponse
#define SOAP_TYPE_ns1__versionResponse (27)
#endif

/* struct ns1__version has binding name 'ns1__version' for type 'ns1:version' */
#ifndef SOAP_TYPE_ns1__version
#define SOAP_TYPE_ns1__version (26)
#endif

/* struct ns1__ArrayOfStrings has binding name 'ns1__ArrayOfStrings' for type 'ns1:ArrayOfStrings' */
#ifndef SOAP_TYPE_ns1__ArrayOfStrings
#define SOAP_TYPE_ns1__ArrayOfStrings (24)
#endif

/* struct ns1__Table has binding name 'ns1__Table' for type 'ns1:Table' */
#ifndef SOAP_TYPE_ns1__Table
#define SOAP_TYPE_ns1__Table (21)
#endif

/* struct ns1__File has binding name 'ns1__File' for type 'ns1:File' */
#ifndef SOAP_TYPE_ns1__File
#define SOAP_TYPE_ns1__File (19)
#endif

/* struct ns1__ArrayOfString has binding name 'ns1__ArrayOfString' for type 'ns1:ArrayOfString' */
#ifndef SOAP_TYPE_ns1__ArrayOfString
#define SOAP_TYPE_ns1__ArrayOfString (17)
#endif

/* struct ns1__Entry has binding name 'ns1__Entry' for type 'ns1:Entry' */
#ifndef SOAP_TYPE_ns1__Entry
#define SOAP_TYPE_ns1__Entry (14)
#endif

/* struct ns1__Entries has binding name 'ns1__Entries' for type 'ns1:Entries' */
#ifndef SOAP_TYPE_ns1__Entries
#define SOAP_TYPE_ns1__Entries (13)
#endif

/* ns1__base64Binary has binding name 'ns1__base64Binary' for type 'ns1:base64Binary' */
#ifndef SOAP_TYPE_ns1__base64Binary
#define SOAP_TYPE_ns1__base64Binary (12)
#endif

/* struct xsd__base64Binary has binding name 'xsd__base64Binary' for type 'xsd:base64Binary' */
#ifndef SOAP_TYPE_xsd__base64Binary
#define SOAP_TYPE_xsd__base64Binary (7)
#endif

/* struct SOAP_ENV__Reason * has binding name 'PointerToSOAP_ENV__Reason' for type '' */
#ifndef SOAP_TYPE_PointerToSOAP_ENV__Reason
#define SOAP_TYPE_PointerToSOAP_ENV__Reason (58)
#endif

/* struct SOAP_ENV__Detail * has binding name 'PointerToSOAP_ENV__Detail' for type '' */
#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_PointerToSOAP_ENV__Detail (57)
#endif

/* struct SOAP_ENV__Code * has binding name 'PointerToSOAP_ENV__Code' for type '' */
#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (51)
#endif

/* struct ns1__reloadResponse * has binding name 'PointerTons1__reloadResponse' for type 'ns1:reloadResponse' */
#ifndef SOAP_TYPE_PointerTons1__reloadResponse
#define SOAP_TYPE_PointerTons1__reloadResponse (46)
#endif

/* struct ns1__reload * has binding name 'PointerTons1__reload' for type 'ns1:reload' */
#ifndef SOAP_TYPE_PointerTons1__reload
#define SOAP_TYPE_PointerTons1__reload (45)
#endif

/* struct ns1__testResponse * has binding name 'PointerTons1__testResponse' for type 'ns1:testResponse' */
#ifndef SOAP_TYPE_PointerTons1__testResponse
#define SOAP_TYPE_PointerTons1__testResponse (42)
#endif

/* struct ns1__test * has binding name 'PointerTons1__test' for type 'ns1:test' */
#ifndef SOAP_TYPE_PointerTons1__test
#define SOAP_TYPE_PointerTons1__test (41)
#endif

/* struct ns1__versionResponse * has binding name 'PointerTons1__versionResponse' for type 'ns1:versionResponse' */
#ifndef SOAP_TYPE_PointerTons1__versionResponse
#define SOAP_TYPE_PointerTons1__versionResponse (38)
#endif

/* struct ns1__version * has binding name 'PointerTons1__version' for type 'ns1:version' */
#ifndef SOAP_TYPE_PointerTons1__version
#define SOAP_TYPE_PointerTons1__version (37)
#endif

/* struct __ns1__execResponse * has binding name 'PointerTo__ns1__execResponse' for type '-ns1:execResponse' */
#ifndef SOAP_TYPE_PointerTo__ns1__execResponse
#define SOAP_TYPE_PointerTo__ns1__execResponse (34)
#endif

/* struct ns1__Entries * has binding name 'PointerTons1__Entries' for type 'ns1:Entries' */
#ifndef SOAP_TYPE_PointerTons1__Entries
#define SOAP_TYPE_PointerTons1__Entries (33)
#endif

/* struct ns1__ArrayOfStrings * has binding name 'PointerTons1__ArrayOfStrings' for type 'ns1:ArrayOfStrings' */
#ifndef SOAP_TYPE_PointerTons1__ArrayOfStrings
#define SOAP_TYPE_PointerTons1__ArrayOfStrings (25)
#endif

/* char ** has binding name 'PointerTons1__string' for type 'ns1:string' */
#ifndef SOAP_TYPE_PointerTons1__string
#define SOAP_TYPE_PointerTons1__string (23)
#endif

/* struct ns1__Table * has binding name 'PointerTons1__Table' for type 'ns1:Table' */
#ifndef SOAP_TYPE_PointerTons1__Table
#define SOAP_TYPE_PointerTons1__Table (22)
#endif

/* struct ns1__File * has binding name 'PointerTons1__File' for type 'ns1:File' */
#ifndef SOAP_TYPE_PointerTons1__File
#define SOAP_TYPE_PointerTons1__File (20)
#endif

/* struct ns1__ArrayOfString * has binding name 'PointerTons1__ArrayOfString' for type 'ns1:ArrayOfString' */
#ifndef SOAP_TYPE_PointerTons1__ArrayOfString
#define SOAP_TYPE_PointerTons1__ArrayOfString (18)
#endif

/* int * has binding name 'PointerToint' for type 'xsd:int' */
#ifndef SOAP_TYPE_PointerToint
#define SOAP_TYPE_PointerToint (16)
#endif

/* struct ns1__Entry * has binding name 'PointerTons1__Entry' for type 'ns1:Entry' */
#ifndef SOAP_TYPE_PointerTons1__Entry
#define SOAP_TYPE_PointerTons1__Entry (15)
#endif

/* ns1__string has binding name 'ns1__string' for type 'ns1:string' */
#ifndef SOAP_TYPE_ns1__string
#define SOAP_TYPE_ns1__string (11)
#endif

/* unsigned char * has binding name 'PointerTounsignedByte' for type 'xsd:unsignedByte' */
#ifndef SOAP_TYPE_PointerTounsignedByte
#define SOAP_TYPE_PointerTounsignedByte (10)
#endif

/* _QName has binding name '_QName' for type 'xsd:QName' */
#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (6)
#endif

/* _XML has binding name '_XML' for type '' */
#ifndef SOAP_TYPE__XML
#define SOAP_TYPE__XML (5)
#endif

/* char * has binding name 'string' for type 'xsd:string' */
#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (4)
#endif

/******************************************************************************\
 *                                                                            *
 * Externals                                                                  *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Client-Side Call Stub Functions                                            *
 *                                                                            *
\******************************************************************************/

    
    /** Web service synchronous operation 'soap_call___ns1__exec' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__exec(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__Entries *ns1__entries, struct __ns1__execResponse *_param_1);
    /** Web service asynchronous operation 'soap_send___ns1__exec' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_send___ns1__exec(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__Entries *ns1__entries);
    /** Web service asynchronous operation 'soap_recv___ns1__exec' to receive a response message from the connected endpoint, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_recv___ns1__exec(struct soap *soap, struct __ns1__execResponse *_param_1);
    
    /** Web service synchronous operation 'soap_call___ns1__version' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__version(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__version *ns1__version, struct ns1__versionResponse *ns1__versionResponse);
    /** Web service asynchronous operation 'soap_send___ns1__version' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_send___ns1__version(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__version *ns1__version);
    /** Web service asynchronous operation 'soap_recv___ns1__version' to receive a response message from the connected endpoint, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_recv___ns1__version(struct soap *soap, struct ns1__versionResponse *ns1__versionResponse);
    
    /** Web service synchronous operation 'soap_call___ns1__test' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__test(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__test *ns1__test, struct ns1__testResponse *ns1__testResponse);
    /** Web service asynchronous operation 'soap_send___ns1__test' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_send___ns1__test(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__test *ns1__test);
    /** Web service asynchronous operation 'soap_recv___ns1__test' to receive a response message from the connected endpoint, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_recv___ns1__test(struct soap *soap, struct ns1__testResponse *ns1__testResponse);
    
    /** Web service synchronous operation 'soap_call___ns1__reload' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__reload(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__reload *ns1__reload, struct ns1__reloadResponse *ns1__reloadResponse);
    /** Web service asynchronous operation 'soap_send___ns1__reload' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_send___ns1__reload(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__reload *ns1__reload);
    /** Web service asynchronous operation 'soap_recv___ns1__reload' to receive a response message from the connected endpoint, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_recv___ns1__reload(struct soap *soap, struct ns1__reloadResponse *ns1__reloadResponse);

#endif

/* End of soapStub.h */
