/* soapClient.c
   Generated by gSOAP 2.8.135 for webservice/ws-cups-fax.h

gSOAP XML Web services tools
Copyright (C) 2000,2024, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#if defined(__BORLANDC__)
#pragma option push -w-8060
#pragma option push -w-8004
#endif
#include "soapH.h"

SOAP_SOURCE_STAMP("@(#) soapClient.c ver 2.8.135 2026-08-26 11:35:10 GMT")


SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__exec(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__Entries *ns1__entries, struct __ns1__execResponse *_param_1)
{	if (soap_send___ns1__exec(soap, soap_endpoint, soap_action, ns1__entries) || soap_recv___ns1__exec(soap, _param_1))
		return soap->error;
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_send___ns1__exec(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__Entries *ns1__entries)
{	struct __ns1__exec soap_tmp___ns1__exec;
	if (soap_endpoint == NULL)
		soap_endpoint = "https://www.gtc-online.de:443/ws-cups-fax/WS";
	if (soap_action == NULL)
		soap_action = "";
	soap_tmp___ns1__exec.ns1__entries = ns1__entries;
	soap_begin(soap);
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize___ns1__exec(soap, &soap_tmp___ns1__exec);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__exec(soap, &soap_tmp___ns1__exec, "-ns1:exec", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__exec(soap, &soap_tmp___ns1__exec, "-ns1:exec", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_recv___ns1__exec(struct soap *soap, struct __ns1__execResponse *_param_1)
{
	if (!_param_1)
		return soap_closesock(soap);
	soap_default___ns1__execResponse(soap, _param_1);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get___ns1__execResponse(soap, _param_1, "-ns1:execResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__version(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__version *ns1__version, struct ns1__versionResponse *ns1__versionResponse)
{	if (soap_send___ns1__version(soap, soap_endpoint, soap_action, ns1__version) || soap_recv___ns1__version(soap, ns1__versionResponse))
		return soap->error;
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_send___ns1__version(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__version *ns1__version)
{	struct __ns1__version soap_tmp___ns1__version;
	if (soap_endpoint == NULL)
		soap_endpoint = "https://www.gtc-online.de:443/ws-cups-fax/WS";
	if (soap_action == NULL)
		soap_action = "";
	soap_tmp___ns1__version.ns1__version = ns1__version;
	soap_begin(soap);
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize___ns1__version(soap, &soap_tmp___ns1__version);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__version(soap, &soap_tmp___ns1__version, "-ns1:version", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__version(soap, &soap_tmp___ns1__version, "-ns1:version", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_recv___ns1__version(struct soap *soap, struct ns1__versionResponse *ns1__versionResponse)
{
	if (!ns1__versionResponse)
		return soap_closesock(soap);
	soap_default_ns1__versionResponse(soap, ns1__versionResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__versionResponse(soap, ns1__versionResponse, "ns1:versionResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__test(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__test *ns1__test, struct ns1__testResponse *ns1__testResponse)
{	if (soap_send___ns1__test(soap, soap_endpoint, soap_action, ns1__test) || soap_recv___ns1__test(soap, ns1__testResponse))
		return soap->error;
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_send___ns1__test(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__test *ns1__test)
{	struct __ns1__test soap_tmp___ns1__test;
	if (soap_endpoint == NULL)
		soap_endpoint = "https://www.gtc-online.de:443/ws-cups-fax/WS";
	if (soap_action == NULL)
		soap_action = "";
	soap_tmp___ns1__test.ns1__test = ns1__test;
	soap_begin(soap);
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize___ns1__test(soap, &soap_tmp___ns1__test);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__test(soap, &soap_tmp___ns1__test, "-ns1:test", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__test(soap, &soap_tmp___ns1__test, "-ns1:test", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_recv___ns1__test(struct soap *soap, struct ns1__testResponse *ns1__testResponse)
{
	if (!ns1__testResponse)
		return soap_closesock(soap);
	soap_default_ns1__testResponse(soap, ns1__testResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__testResponse(soap, ns1__testResponse, "ns1:testResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__reload(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__reload *ns1__reload, struct ns1__reloadResponse *ns1__reloadResponse)
{	if (soap_send___ns1__reload(soap, soap_endpoint, soap_action, ns1__reload) || soap_recv___ns1__reload(soap, ns1__reloadResponse))
		return soap->error;
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_send___ns1__reload(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__reload *ns1__reload)
{	struct __ns1__reload soap_tmp___ns1__reload;
	if (soap_endpoint == NULL)
		soap_endpoint = "https://www.gtc-online.de:443/ws-cups-fax/WS";
	if (soap_action == NULL)
		soap_action = "";
	soap_tmp___ns1__reload.ns1__reload = ns1__reload;
	soap_begin(soap);
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize___ns1__reload(soap, &soap_tmp___ns1__reload);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__reload(soap, &soap_tmp___ns1__reload, "-ns1:reload", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__reload(soap, &soap_tmp___ns1__reload, "-ns1:reload", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_recv___ns1__reload(struct soap *soap, struct ns1__reloadResponse *ns1__reloadResponse)
{
	if (!ns1__reloadResponse)
		return soap_closesock(soap);
	soap_default_ns1__reloadResponse(soap, ns1__reloadResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__reloadResponse(soap, ns1__reloadResponse, "ns1:reloadResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

#if defined(__BORLANDC__)
#pragma option pop
#pragma option pop
#endif

/* End of soapClient.c */
