// Reminder: Modify typemap.dat to customize the header file generated by wsdl2h
/* webservice/ws-cups-fax.h
   Generated by wsdl2h 2.8.135 from https://www.gtc-online.de/ws-cups-fax/WS?wsdl and typemap.dat
   2026-08-26 11:35:10 GMT

   DO NOT INCLUDE THIS ANNOTATED FILE DIRECTLY IN YOUR PROJECT SOURCE CODE.
   USE THE FILES GENERATED BY soapcpp2 FOR YOUR PROJECT'S SOURCE CODE.

gSOAP XML Web services tools
Copyright (C) 2000,2024, Robert van Engelen, Genivia Inc. All Rights Reserved.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

/**

@page page_notes Notes

@note HINTS:
 - Run soapcpp2 on webservice/ws-cups-fax.h to generate the SOAP/XML processing logic:
   Use soapcpp2 -I to specify paths for #import
   Use soapcpp2 -j to generate improved proxy and server classes.
   Use soapcpp2 -r to generate a report.
 - Edit 'typemap.dat' to control namespace bindings and type mappings:
   It is strongly recommended to customize the names of the namespace prefixes
   generated by wsdl2h. To do so, modify the prefix bindings in the Namespaces
   section below and add the modified lines to 'typemap.dat' to rerun wsdl2h.
 - Run Doxygen (www.doxygen.org) on this file to generate documentation.
 - Use wsdl2h -c to generate pure C code.
 - Use wsdl2h -R to include the REST operations defined by the WSDLs.
 - Use wsdl2h -O3 or -O4 to optimize by removing unused schema components.
 - Use wsdl2h -d to enable DOM support for xsd:any and xsd:anyType.
 - Use wsdl2h -F to simulate struct-type derivation in C (also works in C++).
 - Use wsdl2h -f to generate flat C++ class hierarchy, removes type derivation.
 - Use wsdl2h -g to generate top-level root elements with readers and writers.
 - Use wsdl2h -U to map XML names to C++ Unicode identifiers instead of _xNNNN.
 - Use wsdl2h -u to disable the generation of unions.
 - Use wsdl2h -L to remove this @note and all other @note comments.
 - Use wsdl2h -nname to use name as the base namespace prefix instead of 'ns'.
 - Use wsdl2h -Nname for service prefix and produce multiple service bindings
 - Struct/class members serialized as XML attributes are annotated with a '@'.
 - Struct/class members that have a special role are annotated with a '$'.

@warning
   DO NOT INCLUDE THIS ANNOTATED FILE DIRECTLY IN YOUR PROJECT SOURCE CODE.
   USE THE FILES GENERATED BY soapcpp2 FOR YOUR PROJECT'S SOURCE CODE:
   THE GENERATED soapStub.h FILE CONTAINS THIS CONTENT WITHOUT ANNOTATIONS.

@copyright LICENSE:
@verbatim
--------------------------------------------------------------------------------
gSOAP XML Web services tools
Copyright (C) 2000,2024, Robert van Engelen, Genivia Inc. All Rights Reserved.
The wsdl2h tool and its generated software are released under the GPL.
This software is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
GPL license.

This program is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free Software
Foundation; either version 2 of the License, or (at your option) any later
version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with
this program; if not, write to the Free Software Foundation, Inc., 59 Temple
Place, Suite 330, Boston, MA 02111-1307 USA

Author contact information:
engelen@genivia.com / engelen@acm.org

This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial-use license is available from Genivia, Inc., contact@genivia.com
--------------------------------------------------------------------------------
@endverbatim

*/


//gsoapopt c,w

/******************************************************************************\
 *                                                                            *
 * Definitions                                                                *
 *   http://ws.gtc.net/                                                       *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * $SIZE typemap variable:                                                    *
 *   int                                                                      *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Import                                                                     *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Schema Namespaces                                                          *
 *                                                                            *
\******************************************************************************/


/* NOTE:

It is strongly recommended to customize the names of the namespace prefixes
generated by wsdl2h. To do so, modify the prefix bindings below and add the
modified lines to 'typemap.dat' then rerun wsdl2h (use wsdl2h -t typemap.dat):

ns1 = "http://ws.gtc.net/"

*/

#define SOAP_NAMESPACE_OF_ns1	"http://ws.gtc.net/"
//gsoap ns1   schema namespace:	http://ws.gtc.net/
//gsoap ns1   schema elementForm:	qualified
//gsoap ns1   schema attributeForm:	unqualified

/******************************************************************************\
 *                                                                            *
 * Built-in Schema Types and Top-Level Elements and Attributes                *
 *                                                                            *
\******************************************************************************/

/// Built-in type "xs:base64Binary".
struct xsd__base64Binary
{
    unsigned char *__ptr;
    int __size;
    char *id, *type, *options; // NOTE: non-NULL for DIME/MIME/MTOM XOP attachments only
};



/******************************************************************************\
 *                                                                            *
 * Schema Types and Top-Level Elements and Attributes                         *
 *   http://ws.gtc.net/                                                       *
 *                                                                            *
\******************************************************************************/

/// @brief "http://ws.gtc.net/":string is a simpleType restriction of type xs:string.
///
/// Length of this content is 0 to 1024.
typedef char* ns1__string : 1024;

/// @brief "http://ws.gtc.net/":base64Binary is a simpleType restriction of type xs:base64Binary.
///
/// Length of this content is 0 to 67108864.
typedef struct xsd__base64Binary ns1__base64Binary : 67108864;


/******************************************************************************\
 *                                                                            *
 * Schema Complex Types and Top-Level Elements                                *
 *   http://ws.gtc.net/                                                       *
 *                                                                            *
\******************************************************************************/

/// @brief "http://ws.gtc.net/":Entries is a complexType.
///
/// @note struct ns1__Entries operations:
/// - ns1__Entries* soap_new_ns1__Entries(struct soap*, int num) allocate and default initialize one or more values (an array)
/// - soap_default_ns1__Entries(struct soap*, ns1__Entries*) default initialize members
/// - int soap_read_ns1__Entries(struct soap*, ns1__Entries*) deserialize from a source
/// - int soap_write_ns1__Entries(struct soap*, ns1__Entries*) serialize to a sink
/// - ns1__Entries* soap_dup_ns1__Entries(struct soap*, ns1__Entries* dst, ns1__Entries *src) returns deep copy of ns1__Entries src into dst, copies the (cyclic) graph structure when a context is provided, or (cycle-pruned) tree structure with soap_set_mode(soap, SOAP_XML_TREE) (use soapcpp2 -Ec)
/// - soap_del_ns1__Entries(ns1__Entries*) deep deletes ns1__Entries data members, use only on dst after soap_dup_ns1__Entries(NULL, ns1__Entries *dst, ns1__Entries *src) (use soapcpp2 -Ed)
struct ns1__Entries
{
/// Size of array of struct ns1__Entry* is 0..1024.
  $ int                                  __sizeitem                     0:1024;
/// Array struct ns1__Entry* of size 0..1024.
    struct ns1__Entry*                   item                           0:1024;	///< Multiple elements.
};

/// @brief "http://ws.gtc.net/":Entry is a complexType.
///
/// @note struct ns1__Entry operations:
/// - ns1__Entry* soap_new_ns1__Entry(struct soap*, int num) allocate and default initialize one or more values (an array)
/// - soap_default_ns1__Entry(struct soap*, ns1__Entry*) default initialize members
/// - int soap_read_ns1__Entry(struct soap*, ns1__Entry*) deserialize from a source
/// - int soap_write_ns1__Entry(struct soap*, ns1__Entry*) serialize to a sink
/// - ns1__Entry* soap_dup_ns1__Entry(struct soap*, ns1__Entry* dst, ns1__Entry *src) returns deep copy of ns1__Entry src into dst, copies the (cyclic) graph structure when a context is provided, or (cycle-pruned) tree structure with soap_set_mode(soap, SOAP_XML_TREE) (use soapcpp2 -Ec)
/// - soap_del_ns1__Entry(ns1__Entry*) deep deletes ns1__Entry data members, use only on dst after soap_dup_ns1__Entry(NULL, ns1__Entry *dst, ns1__Entry *src) (use soapcpp2 -Ed)
struct ns1__Entry
{
/// Element "key" of type "http://ws.gtc.net/":string.
    ns1__string                          key                            1;	///< Required element.
/// Element "value" of type "http://ws.gtc.net/":string.
    ns1__string                          value                          0;	///< Optional element.
/// Element "intValue" of type xs:int.
    int*                                 intValue                       0;	///< Optional element.
/// Element "values" of type "http://ws.gtc.net/":ArrayOfString.
    struct ns1__ArrayOfString*           values                         0;	///< Optional element.
/// Size of array of struct ns1__File* is 0..10.
  $ int                                  __sizefiles                    0:10;
/// Array struct ns1__File* of size 0..10.
    struct ns1__File*                    files                          0:10;	///< Multiple elements.
/// Element "table" of type "http://ws.gtc.net/":Table.
    struct ns1__Table*                   table                          0;	///< Optional element.
};

/// @brief "http://ws.gtc.net/":ArrayOfString is a complexType.
///
/// @note struct ns1__ArrayOfString operations:
/// - ns1__ArrayOfString* soap_new_ns1__ArrayOfString(struct soap*, int num) allocate and default initialize one or more values (an array)
/// - soap_default_ns1__ArrayOfString(struct soap*, ns1__ArrayOfString*) default initialize members
/// - int soap_read_ns1__ArrayOfString(struct soap*, ns1__ArrayOfString*) deserialize from a source
/// - int soap_write_ns1__ArrayOfString(struct soap*, ns1__ArrayOfString*) serialize to a sink
/// - ns1__ArrayOfString* soap_dup_ns1__ArrayOfString(struct soap*, ns1__ArrayOfString* dst, ns1__ArrayOfString *src) returns deep copy of ns1__ArrayOfString src into dst, copies the (cyclic) graph structure when a context is provided, or (cycle-pruned) tree structure with soap_set_mode(soap, SOAP_XML_TREE) (use soapcpp2 -Ec)
/// - soap_del_ns1__ArrayOfString(ns1__ArrayOfString*) deep deletes ns1__ArrayOfString data members, use only on dst after soap_dup_ns1__ArrayOfString(NULL, ns1__ArrayOfString *dst, ns1__ArrayOfString *src) (use soapcpp2 -Ed)
struct ns1__ArrayOfString
{
/// Size of array of ns1__string* is 0..1024.
  $ int                                  __sizeitem                     0:1024;
/// Array ns1__string* of size 0..1024.
    ns1__string*                         item                           0:1024;	///< Multiple elements.
};

/// @brief "http://ws.gtc.net/":ArrayOfStrings is a complexType.
///
/// @note struct ns1__ArrayOfStrings operations:
/// - ns1__ArrayOfStrings* soap_new_ns1__ArrayOfStrings(struct soap*, int num) allocate and default initialize one or more values (an array)
/// - soap_default_ns1__ArrayOfStrings(struct soap*, ns1__ArrayOfStrings*) default initialize members
/// - int soap_read_ns1__ArrayOfStrings(struct soap*, ns1__ArrayOfStrings*) deserialize from a source
/// - int soap_write_ns1__ArrayOfStrings(struct soap*, ns1__ArrayOfStrings*) serialize to a sink
/// - ns1__ArrayOfStrings* soap_dup_ns1__ArrayOfStrings(struct soap*, ns1__ArrayOfStrings* dst, ns1__ArrayOfStrings *src) returns deep copy of ns1__ArrayOfStrings src into dst, copies the (cyclic) graph structure when a context is provided, or (cycle-pruned) tree structure with soap_set_mode(soap, SOAP_XML_TREE) (use soapcpp2 -Ec)
/// - soap_del_ns1__ArrayOfStrings(ns1__ArrayOfStrings*) deep deletes ns1__ArrayOfStrings data members, use only on dst after soap_dup_ns1__ArrayOfStrings(NULL, ns1__ArrayOfStrings *dst, ns1__ArrayOfStrings *src) (use soapcpp2 -Ed)
struct ns1__ArrayOfStrings
{
/// Size of array of struct ns1__ArrayOfString* is 0..1024.
  $ int                                  __sizeitem                     0:1024;
/// Array struct ns1__ArrayOfString* of size 0..1024.
    struct ns1__ArrayOfString*           item                           0:1024;	///< Multiple elements.
};

/// @brief "http://ws.gtc.net/":File is a complexType.
///
/// @note struct ns1__File operations:
/// - ns1__File* soap_new_ns1__File(struct soap*, int num) allocate and default initialize one or more values (an array)
/// - soap_default_ns1__File(struct soap*, ns1__File*) default initialize members
/// - int soap_read_ns1__File(struct soap*, ns1__File*) deserialize from a source
/// - int soap_write_ns1__File(struct soap*, ns1__File*) serialize to a sink
/// - ns1__File* soap_dup_ns1__File(struct soap*, ns1__File* dst, ns1__File *src) returns deep copy of ns1__File src into dst, copies the (cyclic) graph structure when a context is provided, or (cycle-pruned) tree structure with soap_set_mode(soap, SOAP_XML_TREE) (use soapcpp2 -Ec)
/// - soap_del_ns1__File(ns1__File*) deep deletes ns1__File data members, use only on dst after soap_dup_ns1__File(NULL, ns1__File *dst, ns1__File *src) (use soapcpp2 -Ed)
struct ns1__File
{
/// Element "name" of type "http://ws.gtc.net/":string.
    ns1__string                          name                           1;	///< Required element.
/// Element "data" of type "http://ws.gtc.net/":base64Binary.
    ns1__base64Binary                    data                           1;	///< Required element.
};

/// @brief "http://ws.gtc.net/":Table is a complexType.
///
/// @note struct ns1__Table operations:
/// - ns1__Table* soap_new_ns1__Table(struct soap*, int num) allocate and default initialize one or more values (an array)
/// - soap_default_ns1__Table(struct soap*, ns1__Table*) default initialize members
/// - int soap_read_ns1__Table(struct soap*, ns1__Table*) deserialize from a source
/// - int soap_write_ns1__Table(struct soap*, ns1__Table*) serialize to a sink
/// - ns1__Table* soap_dup_ns1__Table(struct soap*, ns1__Table* dst, ns1__Table *src) returns deep copy of ns1__Table src into dst, copies the (cyclic) graph structure when a context is provided, or (cycle-pruned) tree structure with soap_set_mode(soap, SOAP_XML_TREE) (use soapcpp2 -Ec)
/// - soap_del_ns1__Table(ns1__Table*) deep deletes ns1__Table data members, use only on dst after soap_dup_ns1__Table(NULL, ns1__Table *dst, ns1__Table *src) (use soapcpp2 -Ed)
struct ns1__Table
{
/// Element "head" of type "http://ws.gtc.net/":ArrayOfString.
    struct ns1__ArrayOfString*           head                           1;	///< Required element.
/// Element "fields" of type "http://ws.gtc.net/":ArrayOfStrings.
    struct ns1__ArrayOfStrings*          fields                         1;	///< Required element.
};

/// @brief "http://ws.gtc.net/":version is a complexType.
///
/// @note struct ns1__version operations:
/// - ns1__version* soap_new_ns1__version(struct soap*, int num) allocate and default initialize one or more values (an array)
/// - soap_default_ns1__version(struct soap*, ns1__version*) default initialize members
/// - int soap_read_ns1__version(struct soap*, ns1__version*) deserialize from a source
/// - int soap_write_ns1__version(struct soap*, ns1__version*) serialize to a sink
/// - ns1__version* soap_dup_ns1__version(struct soap*, ns1__version* dst, ns1__version *src) returns deep copy of ns1__version src into dst, copies the (cyclic) graph structure when a context is provided, or (cycle-pruned) tree structure with soap_set_mode(soap, SOAP_XML_TREE) (use soapcpp2 -Ec)
/// - soap_del_ns1__version(ns1__version*) deep deletes ns1__version data members, use only on dst after soap_dup_ns1__version(NULL, ns1__version *dst, ns1__version *src) (use soapcpp2 -Ed)
struct ns1__version
{
};

/// @brief "http://ws.gtc.net/":versionResponse is a complexType.
///
/// @note struct ns1__versionResponse operations:
/// - ns1__versionResponse* soap_new_ns1__versionResponse(struct soap*, int num) allocate and default initialize one or more values (an array)
/// - soap_default_ns1__versionResponse(struct soap*, ns1__versionResponse*) default initialize members
/// - int soap_read_ns1__versionResponse(struct soap*, ns1__versionResponse*) deserialize from a source
/// - int soap_write_ns1__versionResponse(struct soap*, ns1__versionResponse*) serialize to a sink
/// - ns1__versionResponse* soap_dup_ns1__versionResponse(struct soap*, ns1__versionResponse* dst, ns1__versionResponse *src) returns deep copy of ns1__versionResponse src into dst, copies the (cyclic) graph structure when a context is provided, or (cycle-pruned) tree structure with soap_set_mode(soap, SOAP_XML_TREE) (use soapcpp2 -Ec)
/// - soap_del_ns1__versionResponse(ns1__versionResponse*) deep deletes ns1__versionResponse data members, use only on dst after soap_dup_ns1__versionResponse(NULL, ns1__versionResponse *dst, ns1__versionResponse *src) (use soapcpp2 -Ed)
struct ns1__versionResponse
{
/// Element "versionResponse" of type "http://ws.gtc.net/":string.
    ns1__string                          versionResponse                1;	///< Required element.
};

/// @brief "http://ws.gtc.net/":test is a complexType.
///
/// @note struct ns1__test operations:
/// - ns1__test* soap_new_ns1__test(struct soap*, int num) allocate and default initialize one or more values (an array)
/// - soap_default_ns1__test(struct soap*, ns1__test*) default initialize members
/// - int soap_read_ns1__test(struct soap*, ns1__test*) deserialize from a source
/// - int soap_write_ns1__test(struct soap*, ns1__test*) serialize to a sink
/// - ns1__test* soap_dup_ns1__test(struct soap*, ns1__test* dst, ns1__test *src) returns deep copy of ns1__test src into dst, copies the (cyclic) graph structure when a context is provided, or (cycle-pruned) tree structure with soap_set_mode(soap, SOAP_XML_TREE) (use soapcpp2 -Ec)
/// - soap_del_ns1__test(ns1__test*) deep deletes ns1__test data members, use only on dst after soap_dup_ns1__test(NULL, ns1__test *dst, ns1__test *src) (use soapcpp2 -Ed)
struct ns1__test
{
};

/// @brief "http://ws.gtc.net/":testResponse is a complexType.
///
/// @note struct ns1__testResponse operations:
/// - ns1__testResponse* soap_new_ns1__testResponse(struct soap*, int num) allocate and default initialize one or more values (an array)
/// - soap_default_ns1__testResponse(struct soap*, ns1__testResponse*) default initialize members
/// - int soap_read_ns1__testResponse(struct soap*, ns1__testResponse*) deserialize from a source
/// - int soap_write_ns1__testResponse(struct soap*, ns1__testResponse*) serialize to a sink
/// - ns1__testResponse* soap_dup_ns1__testResponse(struct soap*, ns1__testResponse* dst, ns1__testResponse *src) returns deep copy of ns1__testResponse src into dst, copies the (cyclic) graph structure when a context is provided, or (cycle-pruned) tree structure with soap_set_mode(soap, SOAP_XML_TREE) (use soapcpp2 -Ec)
/// - soap_del_ns1__testResponse(ns1__testResponse*) deep deletes ns1__testResponse data members, use only on dst after soap_dup_ns1__testResponse(NULL, ns1__testResponse *dst, ns1__testResponse *src) (use soapcpp2 -Ed)
struct ns1__testResponse
{
/// Element "testResponse" of type xs:int.
    int                                  testResponse                   1;	///< Required element.
};

/// @brief "http://ws.gtc.net/":reload is a complexType.
///
/// @note struct ns1__reload operations:
/// - ns1__reload* soap_new_ns1__reload(struct soap*, int num) allocate and default initialize one or more values (an array)
/// - soap_default_ns1__reload(struct soap*, ns1__reload*) default initialize members
/// - int soap_read_ns1__reload(struct soap*, ns1__reload*) deserialize from a source
/// - int soap_write_ns1__reload(struct soap*, ns1__reload*) serialize to a sink
/// - ns1__reload* soap_dup_ns1__reload(struct soap*, ns1__reload* dst, ns1__reload *src) returns deep copy of ns1__reload src into dst, copies the (cyclic) graph structure when a context is provided, or (cycle-pruned) tree structure with soap_set_mode(soap, SOAP_XML_TREE) (use soapcpp2 -Ec)
/// - soap_del_ns1__reload(ns1__reload*) deep deletes ns1__reload data members, use only on dst after soap_dup_ns1__reload(NULL, ns1__reload *dst, ns1__reload *src) (use soapcpp2 -Ed)
struct ns1__reload
{
};

/// @brief "http://ws.gtc.net/":reloadResponse is a complexType.
///
/// @note struct ns1__reloadResponse operations:
/// - ns1__reloadResponse* soap_new_ns1__reloadResponse(struct soap*, int num) allocate and default initialize one or more values (an array)
/// - soap_default_ns1__reloadResponse(struct soap*, ns1__reloadResponse*) default initialize members
/// - int soap_read_ns1__reloadResponse(struct soap*, ns1__reloadResponse*) deserialize from a source
/// - int soap_write_ns1__reloadResponse(struct soap*, ns1__reloadResponse*) serialize to a sink
/// - ns1__reloadResponse* soap_dup_ns1__reloadResponse(struct soap*, ns1__reloadResponse* dst, ns1__reloadResponse *src) returns deep copy of ns1__reloadResponse src into dst, copies the (cyclic) graph structure when a context is provided, or (cycle-pruned) tree structure with soap_set_mode(soap, SOAP_XML_TREE) (use soapcpp2 -Ec)
/// - soap_del_ns1__reloadResponse(ns1__reloadResponse*) deep deletes ns1__reloadResponse data members, use only on dst after soap_dup_ns1__reloadResponse(NULL, ns1__reloadResponse *dst, ns1__reloadResponse *src) (use soapcpp2 -Ed)
struct ns1__reloadResponse
{
/// Element "reloadResponse" of type xs:int.
    int                                  reloadResponse                 1;	///< Required element.
};


/******************************************************************************\
 *                                                                            *
 * Additional Top-Level Elements                                              *
 *   http://ws.gtc.net/                                                       *
 *                                                                            *
\******************************************************************************/

/// @brief Top-level root element "http://ws.gtc.net/":entries of type "http://ws.gtc.net/":Entries.
/// @note Use wsdl2h option -g to auto-generate a top-level root element declaration.

/// @brief Top-level root element "http://ws.gtc.net/":test of type "http://ws.gtc.net/":test.
/// @note Use wsdl2h option -g to auto-generate a top-level root element declaration.

/// @brief Top-level root element "http://ws.gtc.net/":testResponse of type "http://ws.gtc.net/":testResponse.
/// @note Use wsdl2h option -g to auto-generate a top-level root element declaration.

/// @brief Top-level root element "http://ws.gtc.net/":version of type "http://ws.gtc.net/":version.
/// @note Use wsdl2h option -g to auto-generate a top-level root element declaration.

/// @brief Top-level root element "http://ws.gtc.net/":versionResponse of type "http://ws.gtc.net/":versionResponse.
/// @note Use wsdl2h option -g to auto-generate a top-level root element declaration.

/// @brief Top-level root element "http://ws.gtc.net/":reload of type "http://ws.gtc.net/":reload.
/// @note Use wsdl2h option -g to auto-generate a top-level root element declaration.

/// @brief Top-level root element "http://ws.gtc.net/":reloadResponse of type "http://ws.gtc.net/":reloadResponse.
/// @note Use wsdl2h option -g to auto-generate a top-level root element declaration.


/******************************************************************************\
 *                                                                            *
 * Additional Top-Level Attributes                                            *
 *   http://ws.gtc.net/                                                       *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Services                                                                   *
 *                                                                            *
\******************************************************************************/


//gsoap ns1  service name:	PortBinding 
//gsoap ns1  service type:	WS 
//gsoap ns1  service port:	https://www.gtc-online.de:443/ws-cups-fax/WS 
//gsoap ns1  service namespace:	http://ws.gtc.net/ 
//gsoap ns1  service transport:	http://schemas.xmlsoap.org/soap/http 

/** @mainpage WS Definitions

@section WS_bindings Service Bindings

  - @ref PortBinding

@section WS_more More Information

  - @ref page_notes "Notes"

  - @ref page_XMLDataBinding "XML Data Binding"

  - @ref SOAP_ENV__Header "SOAP Header Content" (when applicable)

  - @ref SOAP_ENV__Detail "SOAP Fault Detail Content" (when applicable)


*/

/** @page PortBinding Binding "PortBinding"

@section PortBinding_operations Operations of Binding "PortBinding"

  - @ref __ns1__exec

  - @ref __ns1__version

  - @ref __ns1__test

  - @ref __ns1__reload

@section PortBinding_ports Default endpoints of Binding "PortBinding"

  - https://www.gtc-online.de:443/ws-cups-fax/WS

@note Use wsdl2h option -Nname to change the service binding prefix name


*/

/******************************************************************************\
 *                                                                            *
 * Service Binding                                                            *
 *   PortBinding                                                              *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Service Operation                                                          *
 *   __ns1__exec                                                              *
 *                                                                            *
\******************************************************************************/

/// Operation response struct "__ns1__execResponse" of operation "__ns1__exec".
struct __ns1__execResponse
{
    struct ns1__Entries*                ns1__entries;	///< Output parameter
};

/** Operation "__ns1__exec" of service binding "PortBinding".

  - SOAP document/literal style messaging

  - Default endpoints:
    - https://www.gtc-online.de:443/ws-cups-fax/WS

  - Addressing input action: ""

  - Addressing output action: "Response"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call___ns1__exec(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // input parameters:
    struct ns1__Entries*                ns1__entries,
    // output parameters:
    struct __ns1__execResponse*
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int __ns1__exec(
    struct soap *soap,
    // input parameters:
    struct ns1__Entries*                ns1__entries,
    // output parameters:
    struct __ns1__execResponse*
  );
@endcode

*/

//gsoap ns1  service method-protocol:	exec SOAP
//gsoap ns1  service method-style:	exec document
//gsoap ns1  service method-encoding:	exec literal
//gsoap ns1  service method-action:	exec ""
//gsoap ns1  service method-output-action:	exec Response
int __ns1__exec(
    struct ns1__Entries*                ns1__entries,	///< Input parameter
    struct __ns1__execResponse         *	///< Output response struct parameter
);

/******************************************************************************\
 *                                                                            *
 * Service Operation                                                          *
 *   __ns1__version                                                           *
 *                                                                            *
\******************************************************************************/


/** Operation "__ns1__version" of service binding "PortBinding".

  - SOAP document/literal style messaging

  - Default endpoints:
    - https://www.gtc-online.de:443/ws-cups-fax/WS

  - Addressing input action: ""

  - Addressing output action: "Response"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call___ns1__version(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // input parameters:
    struct ns1__version*                ns1__version,
    // output parameters:
    struct ns1__versionResponse        *ns1__versionResponse
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int __ns1__version(
    struct soap *soap,
    // input parameters:
    struct ns1__version*                ns1__version,
    // output parameters:
    struct ns1__versionResponse        *ns1__versionResponse
  );
@endcode

*/

//gsoap ns1  service method-protocol:	version SOAP
//gsoap ns1  service method-style:	version document
//gsoap ns1  service method-encoding:	version literal
//gsoap ns1  service method-action:	version ""
//gsoap ns1  service method-output-action:	version Response
int __ns1__version(
    struct ns1__version*                ns1__version,	///< Input parameter
    struct ns1__versionResponse        *ns1__versionResponse	///< Output parameter
);

/******************************************************************************\
 *                                                                            *
 * Service Operation                                                          *
 *   __ns1__test                                                              *
 *                                                                            *
\******************************************************************************/


/** Operation "__ns1__test" of service binding "PortBinding".

  - SOAP document/literal style messaging

  - Default endpoints:
    - https://www.gtc-online.de:443/ws-cups-fax/WS

  - Addressing input action: ""

  - Addressing output action: "Response"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call___ns1__test(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // input parameters:
    struct ns1__test*                   ns1__test,
    // output parameters:
    struct ns1__testResponse           *ns1__testResponse
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int __ns1__test(
    struct soap *soap,
    // input parameters:
    struct ns1__test*                   ns1__test,
    // output parameters:
    struct ns1__testResponse           *ns1__testResponse
  );
@endcode

*/

//gsoap ns1  service method-protocol:	test SOAP
//gsoap ns1  service method-style:	test document
//gsoap ns1  service method-encoding:	test literal
//gsoap ns1  service method-action:	test ""
//gsoap ns1  service method-output-action:	test Response
int __ns1__test(
    struct ns1__test*                   ns1__test,	///< Input parameter
    struct ns1__testResponse           *ns1__testResponse	///< Output parameter
);

/******************************************************************************\
 *                                                                            *
 * Service Operation                                                          *
 *   __ns1__reload                                                            *
 *                                                                            *
\******************************************************************************/


/** Operation "__ns1__reload" of service binding "PortBinding".

  - SOAP document/literal style messaging

  - Default endpoints:
    - https://www.gtc-online.de:443/ws-cups-fax/WS

  - Addressing input action: ""

  - Addressing output action: "Response"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call___ns1__reload(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // input parameters:
    struct ns1__reload*                 ns1__reload,
    // output parameters:
    struct ns1__reloadResponse         *ns1__reloadResponse
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int __ns1__reload(
    struct soap *soap,
    // input parameters:
    struct ns1__reload*                 ns1__reload,
    // output parameters:
    struct ns1__reloadResponse         *ns1__reloadResponse
  );
@endcode

*/

//gsoap ns1  service method-protocol:	reload SOAP
//gsoap ns1  service method-style:	reload document
//gsoap ns1  service method-encoding:	reload literal
//gsoap ns1  service method-action:	reload ""
//gsoap ns1  service method-output-action:	reload Response
int __ns1__reload(
    struct ns1__reload*                 ns1__reload,	///< Input parameter
    struct ns1__reloadResponse         *ns1__reloadResponse	///< Output parameter
);

/** @page PortBinding Binding "PortBinding"

@section PortBinding_policy_enablers Policy Enablers of Binding "PortBinding"

None specified.

*/

/******************************************************************************\
 *                                                                            *
 * XML Data Binding                                                           *
 *                                                                            *
\******************************************************************************/


/** @page page_XMLDataBinding XML Data Binding

SOAP/XML services use data bindings that are contractually bound by WSDLs and
are auto-generated by wsdl2h and soapcpp2 (see Service Bindings). Plain data
bindings are adopted from XML schemas as part of the WSDL types section or when
running wsdl2h on a set of schemas to produce non-SOAP-based XML data bindings.

@note The following readers and writers are C/C++ data type (de)serializers
auto-generated by wsdl2h and soapcpp2. Run soapcpp2 on this file to generate the
(de)serialization code, which is stored in soapC.c[pp]. Include "soapH.h" in
your code to import these data type and function declarations. Only use the
soapcpp2-generated files in your project build. Do not include the wsdl2h-
generated .h file in your code.

@note Data can be read and deserialized from:
  - an int file descriptor, using soap->recvfd = fd
  - a socket, using soap->socket = (int)...
  - a C++ stream (istream, stringstream), using soap->is = (istream*)...
  - a C string, using soap->is = (const char*)...
  - any input, using the soap->frecv() callback

@note Data can be serialized and written to:
  - an int file descriptor, using soap->sendfd = (int)...
  - a socket, using soap->socket = (int)...
  - a C++ stream (ostream, stringstream), using soap->os = (ostream*)...
  - a C string, using soap->os = (const char**)...
  - any output, using the soap->fsend() callback

@note The following options are available for (de)serialization control:
  - soap->encodingStyle = NULL; to remove SOAP 1.1/1.2 encodingStyle
  - soap_set_mode(soap, SOAP_XML_TREE); XML without id-ref (no cycles!)
  - soap_set_mode(soap, SOAP_XML_GRAPH); XML with id-ref (including cycles)
  - soap_set_namespaces(soap, struct Namespace *nsmap); to set xmlns bindings


*/

/**

@section ns1 Top-level root elements of schema "http://ws.gtc.net/"

  - <ns1:entries> (use wsdl2h option -g to auto-generate type _ns1__entries)

  - <ns1:test> (use wsdl2h option -g to auto-generate type _ns1__test)

  - <ns1:testResponse> (use wsdl2h option -g to auto-generate type _ns1__testResponse)

  - <ns1:version> (use wsdl2h option -g to auto-generate type _ns1__version)

  - <ns1:versionResponse> (use wsdl2h option -g to auto-generate type _ns1__versionResponse)

  - <ns1:reload> (use wsdl2h option -g to auto-generate type _ns1__reload)

  - <ns1:reloadResponse> (use wsdl2h option -g to auto-generate type _ns1__reloadResponse)

*/

/* End of webservice/ws-cups-fax.h */
